server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  gzip on; gzip_types text/html application/json;
  location /audio/ { add_header Cache-Control "public, max-age=31536000, immutable"; add_header Accept-Ranges bytes; }
}
